Repository libremesh/lime-packages, pull requests merged in 2019-11, with the labels that each got.

#635 Node config clearly separated from network config
  packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
  packages/first-boot-wizard/tests/test_firstbootwizard.lua
  packages/lime-ap-watchping/files/etc/uci-defaults/91_autoAP
  packages/lime-docs/files/lime-example
  packages/lime-hwd-openwrt-wan/tests/test_lime_hwd_openwrt_wan.lua
  packages/lime-report/files/lime-report.sh
  packages/lime-smart-wifi/files/etc/uci-defaults/90_lime-smart-wifi
  packages/lime-system/Makefile
  packages/lime-system/files/etc/config/lime-community
  packages/lime-system/files/etc/config/lime-defaults
  packages/lime-system/files/etc/config/lime-node
  packages/lime-system/files/etc/uci-defaults/88_lime-merge-factory-defaults
  packages/lime-system/files/lib/upgrade/keep.d/libremesh
  packages/lime-system/files/usr/bin/lime-config
  packages/lime-system/files/usr/bin/lime-sysupgrade
  packages/lime-system/files/usr/lib/lua/lime/config.lua
  packages/lime-system/files/usr/lib/lua/lime/utils.lua
  packages/lime-system/files/usr/lib/lua/lime/wireless.lua
  packages/lime-system/tests/test_lime_config.lua
  packages/lime-system/tests/test_lime_utils.lua
  packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw
  packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
  tests/test_lime_config_device.lua
  tests/test_test_utils.lua
  tests/utils.lua
Labels: enhancement

#639 FirstBootWizard use uci instead of /etc/first_run
  packages/first-boot-wizard/files/bin/firstbootwizard
  packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
  packages/first-boot-wizard/tests/test_firstbootwizard.lua
  packages/lime-system/files/etc/config/lime-defaults
  packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw
Labels: enhancement, fbw

#636 Option to ignore devices in shared-state-presist
  packages/shared-state-persist/files/usr/bin/shared-state-persist
Labels: soporteremoto

#654 anygw: use dnsmasq host-record instead of address
  packages/lime-proto-anygw/files/usr/lib/lua/lime/proto/anygw.lua
Labels: bug
