Repository libremesh/lime-packages, pull requests merged in 2020-12, with the labels that each got.

#814 fbw: share lime-community as cgi-bin
  packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
  packages/first-boot-wizard/files/www/cgi-bin/lime/lime-community
  packages/first-boot-wizard/files/www/lime-community
Labels: OpenWrt 19.07, bug

#817 Fix some Lime-App dependencies
  packages/lime-app/Makefile
Labels: bug

#818 github-ci: replace deprecated set-env
  .github/workflows/build.yml
Labels: bug

#753 lime-ap-watchping add dependency from lime-system
  packages/lime-ap-watchping/Makefile
Labels: bug

#775 Update category of packages to category in libremesh.mk, de-hardcode lime-system dependency and review lime-system dependency
  libremesh.mk
  packages/bandwidth-test/Makefile
  packages/batman-adv-auto-gw-mode/Makefile
  packages/bmx6-auto-gw-mode/Makefile
  packages/bmx7-auto-gw-bw-mode/Makefile
  packages/bmx7-auto-gw-mode/Makefile
  packages/check-date-http/Makefile
  packages/first-boot-wizard/Makefile
  packages/hotplug-initd-services/Makefile
  packages/lime-ap-watchping/Makefile
  packages/lime-app/Makefile
  packages/lime-debug/Makefile
  packages/lime-docs/Makefile
  packages/lime-hwd-ground-routing/Makefile
  packages/lime-hwd-openwrt-wan/Makefile
  packages/lime-hwd-usbradio/Makefile
  packages/lime-map-agent/Makefile
  packages/lime-proto-anygw/Makefile
  packages/lime-proto-bgp/Makefile
  packages/lime-proto-olsr/Makefile
  packages/lime-proto-olsr2/Makefile
  packages/lime-proto-olsr6/Makefile
  packages/lime-report/Makefile
  packages/lime-smart-wifi/Makefile
  packages/lime-system/Makefile
  packages/lime-webui/Makefile
  packages/shared-state-babeld_hosts/Makefile
  packages/shared-state-bat_hosts/Makefile
  packages/shared-state-dnsmasq_hosts/Makefile
  packages/shared-state-dnsmasq_leases/Makefile
  packages/shared-state-nodes_and_links/Makefile
  packages/shared-state-persist/Makefile
  packages/shared-state-pirania/Makefile
  packages/shared-state/Makefile
  packages/ubus-lime-groundrouting/Makefile
  packages/ubus-lime-location/Makefile
  packages/ubus-lime-metrics/Makefile
  packages/ubus-lime-openairview/Makefile
  packages/ubus-lime-utils/Makefile
Labels: bug, refactoring

#828 Add lua remote debugging instructions
  HACKING.md
Labels: enhancement

#832 lime-utils: remove debugging print
  packages/ubus-lime-utils/files/usr/lib/lua/lime/upgrade.lua
Labels: bug

#811 Fix pirania missing dependency on shared-state-pirania
  packages/pirania/Makefile
Labels: bug
