Repository libremesh/lime-packages, pull requests merged in 2020-10, with the labels that each got.

#772 Improvements to lime-sysupgrade
  packages/lime-system/files/usr/bin/lime-sysupgrade
Labels: bug

#679 Specify the location of cotonete code
  packages/cotonete/README.md
Labels: enhancement

#782 SSH banner: Added pointer to offline documentation in /docs
  packages/lime-docs/Makefile
  packages/lime-docs/files/etc/uci-defaults/91_lime-docs-banner
  packages/lime-docs/files/www/docs/lime-example.txt
Labels: enhancement

#781 Add network-profiles packages repo to OPKG feeds
  packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
Labels: enhancement

#774 configs: ship configs in usr/share and populate if needed
  packages/lime-system/Makefile
  packages/lime-system/files/usr/lib/lua/lime/config.lua
  packages/lime-system/files/usr/share/lime/configs/lime-community
  packages/lime-system/files/usr/share/lime/configs/lime-node
Labels: enhancement

#783 Some Qemu fixes
  tools/qemu_dev_start
Labels: bug

#779 libremesh.mk: allow change of SECTION/CATEGORY
  libremesh.mk
Labels: enhancement

#793 LimeApp updated to v0.2.10
  packages/lime-app/Makefile
Labels: bug

#791 firstbootwizard: now needs root privilege to run
  packages/ubus-lime-fbw/files/usr/share/rpcd/acl.d/lime-fbw.json
Labels: bug

#792 Fbw add dismiss option
  packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
  packages/first-boot-wizard/tests/test_firstbootwizard.lua
  packages/lime-docs/files/www/docs/lime-example.txt
  packages/lime-system/files/etc/config/lime-defaults
  packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw
  packages/ubus-lime-fbw/files/usr/share/rpcd/acl.d/lime-fbw.json
Labels: enhancement

#745 Fbw do not start scann networks at boot
  packages/first-boot-wizard/files/etc/init.d/firstbootwizard
  packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
  packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw
Labels: enhancement, fbw

#697 lime-report fix dmesg command and add info on firewalls
  packages/lime-report/files/lime-report.sh
Labels: bug
