Repository libremesh/lime-packages, pull requests merged in 2020-02, with the labels that each got.

#686 utils: adds unsafe_shell() and shell_quote() functions
  packages/lime-system/files/usr/lib/lua/lime/utils.lua
  packages/lime-system/tests/test_lime_utils.lua
Labels: enhancement

#690 recover limeapp index page
  packages/lime-app/Makefile
Labels: bug

#687 Add helper functions to write rpcd tests and some ubus-lime-utils tests
  .luacov
  packages/lime-system/files/usr/lib/lua/lime/utils.lua
  packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
  packages/ubus-lime-utils/tests/test_lime_utils.lua
  tests/fakes/ubus.lua
  tests/utils.lua
Labels: enhancement, in progress
